import json

race = {
    "track": "Soft5",
    "date": null,
    "race_no": 1,
    "distance": 1700,
    "race_class": "MDN",
    "condition": "Soft5",
    "rail": "True",
    "prize": 27000,
    "field_size": 11,
    "weather": "ocast",
    "bias_notes": null,
    "runners": [
        {
            "number": 1,
            "name": "Habib Albi",
            "barrier": 10,
            "weight": 59,
            "jockey": "Mikayla Weir",
            "trainer": "Aiden St Vincent",
            "sire": "ILOVETHISCITY",
            "last5": "6x3530",
            "dist_record": "W 6.47% P 22%",
            "wet_form": "0-0-2",
            "odds": 15.0,
            "gear": "Stallion Chain",
            "notes": "Forgive last start. Battling maiden.",
            "running_style": "LEADER",
            "last600": 36.28,
            "factor_scores": {"SPD": 60, "PACE": 80, "SECT": 60, "CLASS": 65, "SUIT": 65, "PREP": 70, "DRAW": 60, "JT": 60, "GEAR": 50, "BREED": 50},
            "form_lines": [], "flags": []
        },
        {
            "number": 2,
            "name": "Cook My Goose",
            "barrier": 5,
            "weight": 58,
            "jockey": "Grady Spokes",
            "trainer": "Sally Taylor",
            "sire": "ZOUSAIN",
            "last5": "7x524",
            "dist_record": null,
            "wet_form": "0-1-0",
            "odds": 9.0,
            "gear": "Tongue Tie",
            "notes": "Can improve, minor spot.",
            "running_style": "MIDFIELD",
            "last600": 36.28,
            "factor_scores": {"SPD": 70, "PACE": 75, "SECT": 70, "CLASS": 65, "SUIT": 70, "PREP": 75, "DRAW": 60, "JT": 65, "GEAR": 50, "BREED": 50},
            "form_lines": [], "flags": []
        },
        {
            "number": 3,
            "name": "Taga Smile",
            "barrier": 1,
            "weight": 57.5,
            "jockey": "Nick Heywood",
            "trainer": "Kris Lees",
            "sire": "TAGALOA",
            "last5": "6x224",
            "dist_record": null,
            "wet_form": "0-0-0",
            "odds": 2.5,
            "gear": null,
            "notes": "Top jockey. Good trainer. Close 3rd last start. Hard to beat.",
            "running_style": "ON-PACE",
            "last600": 36.72,
            "factor_scores": {"SPD": 85, "PACE": 80, "SECT": 75, "CLASS": 75, "SUIT": 80, "PREP": 85, "DRAW": 80, "JT": 90, "GEAR": 50, "BREED": 60},
            "form_lines": [], "flags": []
        },
        {
            "number": 4,
            "name": "At Church",
            "barrier": 2,
            "weight": 57,
            "jockey": "Archie Mccolm",
            "trainer": "Ridge Wilson",
            "sire": "CHURCHILL",
            "last5": "59x05",
            "dist_record": null,
            "wet_form": "0-0-0",
            "odds": 21.0,
            "gear": "Nose Roll",
            "notes": "3rd up. Minor place chance.",
            "running_style": "MIDFIELD",
            "last600": 40.07,
            "factor_scores": {"SPD": 60, "PACE": 70, "SECT": 60, "CLASS": 65, "SUIT": 60, "PREP": 65, "DRAW": 60, "JT": 60, "GEAR": 50, "BREED": 50},
            "form_lines": [], "flags": []
        },
        {
            "number": 5,
            "name": "Durness",
            "barrier": 8,
            "weight": 57,
            "jockey": "Ben Looker",
            "trainer": "Colt Prosser",
            "sire": "ARDROSSAN",
            "last5": "958x4",
            "dist_record": null,
            "wet_form": "0-1-0",
            "odds": 4.5,
            "gear": "Blinkers",
            "notes": "Strong 2nd last start here. Peaking.",
            "running_style": "BACKMARKER",
            "last600": 38.34,
            "factor_scores": {"SPD": 80, "PACE": 70, "SECT": 80, "CLASS": 70, "SUIT": 80, "PREP": 85, "DRAW": 50, "JT": 75, "GEAR": 70, "BREED": 50},
            "form_lines": [], "flags": []
        },
        {
            "number": 7,
            "name": "Finding Elle",
            "barrier": 9,
            "weight": 57,
            "jockey": "Raymond Spokes",
            "trainer": "John Higgins",
            "sire": "SHOOTING TO WIN",
            "last5": "48575",
            "dist_record": null,
            "wet_form": "0-1-1",
            "odds": 31.0,
            "gear": "Blinkers",
            "notes": "34 start maiden.",
            "running_style": "MIDFIELD",
            "last600": 38.34,
            "factor_scores": {"SPD": 65, "PACE": 60, "SECT": 65, "CLASS": 55, "SUIT": 60, "PREP": 75, "DRAW": 60, "JT": 60, "GEAR": 50, "BREED": 50},
            "form_lines": [], "flags": []
        },
        {
            "number": 8,
            "name": "Happy Coffee",
            "barrier": 3,
            "weight": 57,
            "jockey": "Bailey Wheeler",
            "trainer": "James Moore",
            "sire": "COSMIC FORCE",
            "last5": "5848x",
            "dist_record": null,
            "wet_form": "0-0-2",
            "odds": 26.0,
            "gear": "Blinkers",
            "notes": "First time blinkers. 23 start maiden.",
            "running_style": "MIDFIELD",
            "last600": 36.72,
            "factor_scores": {"SPD": 60, "PACE": 70, "SECT": 60, "CLASS": 55, "SUIT": 60, "PREP": 65, "DRAW": 60, "JT": 70, "GEAR": 75, "BREED": 50},
            "form_lines": [], "flags": []
        },
        {
            "number": 9,
            "name": "Lagavulin",
            "barrier": 4,
            "weight": 57,
            "jockey": "Frederick Larson",
            "trainer": "Andrew Parramore",
            "sire": "JABALI",
            "last5": "7876",
            "dist_record": null,
            "wet_form": "0-0-0",
            "odds": 101.0,
            "gear": null,
            "notes": "No form.",
            "running_style": "MIDFIELD",
            "last600": 37.25,
            "factor_scores": {"SPD": 40, "PACE": 60, "SECT": 40, "CLASS": 40, "SUIT": 40, "PREP": 50, "DRAW": 60, "JT": 50, "GEAR": 50, "BREED": 50},
            "form_lines": [], "flags": []
        },
        {
            "number": 10,
            "name": "Play It Cool",
            "barrier": 11,
            "weight": 57,
            "jockey": "Danny Peisley",
            "trainer": "David Matts",
            "sire": "COOL AZA BEEL",
            "last5": "70x62",
            "dist_record": null,
            "wet_form": "0-0-0",
            "odds": 41.0,
            "gear": "Blinkers",
            "notes": "10 start maiden.",
            "running_style": "MIDFIELD",
            "last600": 38.34,
            "factor_scores": {"SPD": 60, "PACE": 65, "SECT": 60, "CLASS": 60, "SUIT": 60, "PREP": 65, "DRAW": 60, "JT": 60, "GEAR": 50, "BREED": 50},
            "form_lines": [], "flags": []
        },
        {
            "number": 11,
            "name": "Sajjetti",
            "barrier": 6,
            "weight": 57,
            "jockey": "Harrison Shaw",
            "trainer": "Stephen & Jordan Lee",
            "sire": "INVADER",
            "last5": "00753",
            "dist_record": null,
            "wet_form": "0-0-1",
            "odds": 31.0,
            "gear": "Winkers",
            "notes": "Off Midfield. Placed on heavy last start.",
            "running_style": "MIDFIELD",
            "last600": 38.76,
            "factor_scores": {"SPD": 60, "PACE": 65, "SECT": 60, "CLASS": 60, "SUIT": 60, "PREP": 65, "DRAW": 60, "JT": 60, "GEAR": 50, "BREED": 50},
            "form_lines": [], "flags": []
        },
        {
            "number": 12,
            "name": "Turpin's Torment",
            "barrier": 7,
            "weight": 57,
            "jockey": "Cassey Williams",
            "trainer": "Robert Knight",
            "sire": "FIGHTING SUN",
            "last5": "47823",
            "dist_record": null,
            "wet_form": "0-2-3",
            "odds": 81.0,
            "gear": "Blinkers",
            "notes": "52 start maiden.",
            "running_style": "BACKMARKER",
            "last600": 37.37,
            "factor_scores": {"SPD": 50, "PACE": 50, "SECT": 50, "CLASS": 40, "SUIT": 50, "PREP": 65, "DRAW": 60, "JT": 60, "GEAR": 50, "BREED": 50},
            "form_lines": [], "flags": []
        }
    ]
}

with open("race.json", "w") as f:
    json.dump(race, f, indent=2)
